id: 9055f9baf0ca4f96b22070bf98fc9cf8
initial_creation_type: ocr
source_metadata:
  volumes:
    d6ebf20a1d514efb90a9f915c19dfeb2:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ''
      total_pages: 1953
      volume_number: 27
